# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  
  N = 8
  (1..N).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|

      # All this runs is cfssl, so keep it very light.
      if machine_id == 1
        machine.vm.hostname = "ca"

        machine.vm.provider "virtualbox" do |v|
          v.memory = 512
          v.cpus = 1
        end
      end

      # These are the control nodes, so they need some
      # resources, but we need not be excessive here.
      if machine_id > 1 && machine_id <= 4
        machine.vm.hostname = "control#{machine_id - 1}"

        machine.vm.provider "virtualbox" do |v|
          v.memory = 1024
          v.cpus = 1
        end
      end

      # These are the worker nodes that we will actually
      # schedule on, so we would like them to be the
      # heaviest.
      if machine_id > 4 && machine_id <= N
        machine.vm.hostname = "compute#{machine_id - 4}"

        machine.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
      end

      machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          ansible.compatibility_mode = "2.0"

          ansible.playbook            = "playbook.yml"
          ansible.limit               = "all"
          ansible.become              = true
          ansible.vault_password_file = "pwd.txt"
          
          ansible.groups = {
            "ca" => [ "machine1" ],
            "hashicorp" => [ "machine2", "machine3", "machine4", "machine5", "machine6", "machine7", "machine8" ],
            "control" => [ "machine2", "machine3", "machine4" ],
            "compute" => [ "machine5", "machine6", "machine7", "machine8" ],
            "vagrant" => [ "machine1", "machine2", "machine3", "machine4", "machine5", "machine6", "machine7", "machine8" ]
          }
        end
      end
    end
  end
end
