# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  
  N = 4
  (1..N).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|

      if N == 1
        machine.vm.hostname = "ca"
      end

      if N > 1 and N <= 4
        machine.vm.hostname = "control#{machine_id - 1}"
      end

      if N <= 4
        machine.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
      end

      machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          ansible.compatibility_mode = "2.0"

          ansible.playbook = "playbook.yml"
          ansible.limit = "all"
          ansible.become = true
          
          ansible.groups = {
            "ca" => [ "machine1" ],
            "consul" => [ "machine2", "machine3", "machine4" ]
          }
        end
      end
    end
  end
end
